spring.application.name=bogotacup

spring.datasource.url=jdbc:mariadb://3.144.86.252/BogotaCup

spring.datasource.driver-class-name=org.mariadb.jdbc.Driver

spring.datasource.username=root
spring.datasource.password=Niko0803#
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MariaDBDialect
spring.jpa.hibernate.ddl-auto=update

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=bogotacup@gmail.com
spring.mail.password=baoaasrhxovnywhb
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true